# Generated by Django 5.0.1 on 2025-04-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_base64",
            field=models.TextField(blank=True, null=True, verbose_name="avatar"),
        ),
    ]
